
name: 'StandardRB Action'
description: 'A GitHub Action that lints your Ruby code with StandardRB!'
author: 'Aaron Wortham <wortham.aaron@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'code'
  color: 'gray-dark'
